### ISSUE TITLE
Status bar and lock screen are still English

### ISSUE THREAD

**Issue by thienteakee** [Belmont-Gabriel/MIUI-10-XML-Vietnamese#17]
En: Status bar and lock screen are still English. Please fix it.
Vi: Thanh trạng thái và màn hình khóa vẫn là tiếng Anh trong khi ngôn ngữ hệ thống là tiếng Việt. Sửa lỗi dùm mình nhé.

**Comment by trantuananh1996** [comment]
Bạn cập nhật lên rom cao hơn nhé

**Comment by thienteakee** [comment]
Mình đang sử dụng bản 10.0.5.0, check OTA thì không thấy báo có cập nhật. Có bản mới hơn bản của mình không?

**Comment by trantuananh1996** [comment]
Bạn chủ động vào xiaomi.eu cập nhật nhé

**Comment by thienteakee** [comment]
À đúng rồi, ở phần weekly có bản 10.0.8.1 rồi. Cảm ơn bạn nhé
