### ISSUE TITLE
wrong dictation at Vietnamese/main/Settings.apk/res/values-vi/strings.xml

### ISSUE THREAD

**Issue by baocaosu** [Belmont-Gabriel/MIUI-10-XML-Vietnamese#42]
I found at Settings.apk/res/values-vi/strings.xml
Line 1141 <string name="wifi_ip_address">Địa chỉa IP</string>
String "Địa chỉa IP" needs to be changed to "Địa chỉ IP"
Thank you

**Comment by trantuananh1996** [comment]
Thanks for report. Fixed for next release
