### ISSUE TITLE
chưa đầy đủ tiếng việt trong các ứng dụng cài đặt,bảo mật....

### ISSUE THREAD

**Issue by newface14k** [Belmont-Gabriel/MIUI-10-XML-Vietnamese#8]
chưa đầy đủ tiếng việt trong các ứng dụng cài đặt,bảo mật....

**Comment by trantuananh1996** [comment]
Đã dịch nhưng xiaomi.eu chưa update

**Comment by newface14k** [comment]
Bác cho e hỏi chỉnh độ cao thanh thông báo ở file nào? Fit notch status bar
mi8

Vào 17:56, Th 6, 2 thg 11, 2018 Trần Anh <notifications@github.com đã viết:
